#!/bin/bash

CLASSPATH="-cp .:lib/command-line.jar"

clear
# Remove *.class files if they exist
if [ -f *.class ]; then
  rm *.class
fi

# Runs program
javac $CLASSPATH *.java
java $CLASSPATH Manager $@

# Clean up after running
rm *.class
